angular
.module("junkBox.services",
  [
    "junkBox.services.homeService",
    "junkBox.services.queriesService",
    "junkBox.services.preferencesService",
    "junkBox.services.ebayService",
    "junkBox.services.orderHistoryService"
  ]);