//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindingAPI_WebApp_Sample {
    
    public partial class _Default {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.TextBox txtKeywords;
        protected System.Web.UI.WebControls.Button btn_SOAPSearch;
        protected System.Web.UI.WebControls.TextBox txtResult;
    }
}
